---
abstract: 'Find a parser class for a database connection.'
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-DBI
no_index:
  directory: eg
provides:
  DateTime::Format::DBI:
    file: lib/DateTime/Format/DBI.pm
    version: 0.039_20101017
recommends:
  Test::Database: 0
requires:
  DBI: 1.21
  DateTime: 0.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.039_20101017
